site_name: Notes
nav: 
  - Ansible: 
    - Installer: ansible.md
    - Commandes et playbook: ansible_commands.md

  - Python:
    - Créer un environnement virtuel: pip_venv.md

  - LINUX:
    - Commandes à connaitre: commandes_rhel.md
    - Kickstart: kickstart.md
    - Preseed: preseed.md
    - Gestion de packets: packet.md
    - Repository: repo.md
    - Boot process: boot.md
    - Firewall: firewall.md
    - Réinitialiser mot de passe root: root_password.md
    - Emergency mode: emergency.md
    - Regex: shell-expansion.md
    - Création de clés privées: ssh_keys.md
    - Crontab: crontab.md
    - Container: container.md
    - SELinux: selinux.md
    - Chrony: chrony.md
    - Log: log.md
    - SSH: ssh.md
    - Hostname: hostname.md
    - umask: umask.md
    - Process priority: priority.md
    - Stockage basique: basic_storage.md
    - Swap: swap.md
    - NFS: nfs.md
    - Créer et resize un LVM: create_lvm.md
    - Stratis: stratis.md
  
  - SSL/TLS:
    - Fonctionnement: ssl.md

  - Apache:
    - Configurer apache: apache.md

  - Nagios:
    - Serveur: nagios_server.md
    - Client ncpa: nagios_ncpa.md

  - Git:
    - Commandes git: git_commands.md

  - Azure:
    - Services: services.md
    



theme: readthedocs

